{% set name = "jupyterlab-unfold" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_unfold-{{ version }}.tar.gz
  sha256: bb8cdf84295dfdadaf76b115251b6a3b5e34d40f6e53336ff4cd4b7e80951c09

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - yarn
    - hatchling
    - hatch-jupyter-builder
    - hatch-nodejs-version
    - jupyterlab >=4,<5
    - jupyter-packaging >=0.10,<2
  run:
    - python >=3.6
  run_constrained:
    - jupyterlab >=4,<5

test:
  commands:
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyterlab-unfold/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-unfold\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-unfold
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An IDE-like file browser for JupyterLab
  dev_url: https://github.com/jupyterlab-contrib/jupyterlab-unfold

extra:
  recipe-maintainers:
    - martinRenou
    - jupyterlab-contrib-bot
