{% set name = "jupyterlab-unfold" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_unfold-{{ version }}.tar.gz
  sha256: 4573debbb07b77fcb17a2663025fa02a3d7b0f19965b27c2d73c36fcbe969147

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - yarn
    - hatchling
    - hatch-jupyter-builder
    - hatch-nodejs-version
    - jupyterlab >=4,<5
    - jupyter-packaging >=0.10,<2
  run:
    - python >={{ python_min }}
  run_constrained:
    - jupyterlab >=4,<5

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyterlab-unfold/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-unfold\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-unfold
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An IDE-like file browser for JupyterLab
  dev_url: https://github.com/jupyterlab-contrib/jupyterlab-unfold

extra:
  recipe-maintainers:
    - martinRenou
    - jupyterlab-contrib-bot
